source 'https://github.com/aldo-dev/mPodSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'AppSyncWrapper_Example' do
  pod 'AppSyncWrapper', :path => '../'

  target 'AppSyncWrapper_Tests' do
    inherit! :search_paths
  end
end
